# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Tribuo CI (Windows x86_64, OpenJDK 8, Java SE 17, 21, 23)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        # test against supported LTS versions and latest
        java: [ 21, 23 ]
    name: Windows Java SE ${{ matrix.java }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Oracle Java SE
        uses: oracle-actions/setup-java@v1.4.0
        with:
          java-version: ${{ matrix.java }}
      - name: Build with Maven
        run: mvn -B package --file pom.xml
  build-8:
    runs-on: windows-latest
    name: Windows OpenJDK 8
    steps:
      - uses: actions/checkout@v4
      - name: Setup OpenJDK
        uses: actions/setup-java@v4
        with:
          java-version: 8
      - name: Build with OpenJDK 8
        run: mvn -B package --file pom.xml
  build-17:
    runs-on: windows-latest
    name: Windows Java SE 17
    steps:
      - uses: actions/checkout@v4
      - name: Setup Oracle Java SE
        uses: oracle-actions/setup-java@v1.4.0
        with:
          website: oracle.com
          release: 17
          version: 17.0.12
      - name: Build with Java 17
        run: mvn -B package --file pom.xml
